[package]
name = "snowbinary"
version = "0.0.1"
authors = ["harmless-tech"]
edition = "2018"
description = "A system for writing and reading binary files."
documentation = "TODO URL"
readme = "README.md"
homepage = "TODO URL"
repository = "https://github.com/harmless-tech/snowbinary"
# license = "MIT License - Copyright (c) 2021 harmless-tech"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
