[package]
name = "snowbinary"
version = "0.2.0"
authors = ["harmless-tech"]
edition = "2021"
description = "A system for writing and reading binary files using its own format."
readme = "README.md"
repository = "https://github.com/harmless-tech/snowbinary"
license = "MIT"
keywords = ["file"]
exclude = [".github/*", "rustfmt.toml", "target/*", ".gitignore", "Cargo.lock"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seahash = { version = "4.1.0", optional = true }

[features]
default = []
v_hash = ["seahash"]

[workspace]
members = ["crates/*"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
