name: Rust Build, Test, and Create Release
#TODO Auto publish to crates.io?

on:
  push:
    tags:
      - "v**"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [ build-linux, build-macos, build-windows ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-tag
        with:
          text: ${{ github.ref }}
          regex: '^refs\/tags\/v\d+\.\d+\.\d+$'
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          prerelease: ${{ steps.regex-tag.outputs.match == '' }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Run tests
        run: cargo test --verbose --workspace --release
      - name: Build
        run: cargo build --verbose --workspace --release
      - name: Run tests (v_hash)
        run: cargo test --verbose --workspace --release --features v_hash
      - name: Build (v_hash)
        run: cargo build --verbose --workspace --release --features v_hash

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Run tests
        run: cargo test --verbose --workspace --release
      - name: Build
        run: cargo build --verbose --workspace --release
      - name: Run tests (v_hash)
        run: cargo test --verbose --workspace --release --features v_hash
      - name: Build (v_hash)
        run: cargo build --verbose --workspace --release --features v_hash

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Run tests
        run: cargo test --verbose --workspace --release
      - name: Build
        run: cargo build --verbose --workspace --release
      - name: Run tests (v_hash)
        run: cargo test --verbose --workspace --release --features v_hash
      - name: Build (v_hash)
        run: cargo build --verbose --workspace --release --features v_hash
