name: Rust Build and Test
#TODO Switch to alt rust tooling
#TODO Add formatting check for pull requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Run tests
        run: cargo test --verbose --workspace
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests (v_hash)
        run: cargo test --verbose --workspace --features v_hash
      - name: Build (v_hash)
        run: cargo build --verbose --workspace --features v_hash

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Run tests
        run: cargo test --verbose --workspace
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests (v_hash)
        run: cargo test --verbose --workspace --features v_hash
      - name: Build (v_hash)
        run: cargo build --verbose --workspace --features v_hash

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Run tests
        run: cargo test --verbose --workspace
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests (v_hash)
        run: cargo test --verbose --workspace --features v_hash
      - name: Build (v_hash)
        run: cargo build --verbose --workspace --features v_hash
